mongodb/docs-kafka-connector

.gitignore, source/sink-connector/configuration-properties/error-handling.txt
Tip for reviewer: select and apply "hide whitespace" in the diff to find the content changes.
JIRA - <https://jira.mongodb.org/browse/DOCSP-19689>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-19689-error-tolerance-fix/sink-connector/configuration-properties/error-handling/
=> DOCSP-19689: fix sink connector error tolerance description

source/source-connector/configuration-properties/kafka-topic.txt, source/source-connector/configuration-properties/mongodb-connection.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-20958>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-20958-monospace-default-values/source-connector/configuration-properties/all-properties/>
=> DOCSP-20958: update default values to monospace

.github/pull_request_template.md
Fix link to 10gen repo in PR template
JIRA - None
=> remove link to 10gen repo in pr review template

source/includes/source-connector-change-stream.rst, source/source-connector.txt, source/source-connector/fundamentals/change-streams.txt
I didn't believe that the CDC handler data in the initial ticket should be applied to the top level Sink connector page as AFAICT you do not need to apply a CDC handler to a connector, it is an [optional](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-22974/tutorials/sink-connector/#configure-the-sink-connector) configuration. Let me know if you disagree!
Duplicate important info on how sink/source connector work from fundamentals pages to top level pages.
[JIRA](https://jira.mongodb.org/browse/DOCSP-22974)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-22974/source-connector/)
=> (DOCSP-22974) Move Connector Info

source/includes/usage-examples/copy/source.properties, source/source-connector/configuration-properties.txt, source/source-connector/configuration-properties/all-properties.txt, source/source-connector/configuration-properties/copy-existing.txt, source/source-connector/configuration-properties/startup-properties.txt, source/source-connector/configuration-properties/startup.txt, source/source-connector/usage-examples/copy-existing-data.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26355
**Staging**
Main page: https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-26355-start-specified-time/source-connector/configuration-properties/startup/
Old page (added admonition): https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-26355-start-specified-time/source-connector/configuration-properties/copy-existing/
What's New: https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-26355-start-specified-time/whats-new/#std-label-kafka-connector-whats-new-1.9
Usage example: https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connecto …
=> DOCSP-26355: startup mode

source/source-connector/configuration-properties/change-stream.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26559
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-26559-clarify-full-doc/source-connector/configuration-properties/change-stream/#settings
(note in `publish.full.document.only`)
=> DOCSP-26559: clarify what full document property does

source/source-connector/configuration-properties/startup.txt
https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/startup-list-fix/source-connector/configuration-properties/startup/#std-label-source-configuration-startup:~:text=startup.mode.timestamp.start.at.operation.time
=> list format fix

source/includes/m1-incompatibility.rst, source/quick-start.txt
Applies to docs v1.8 and later per the ticket description.
JIRA - <https://jira.mongodb.org/browse/DOCS-15819>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCS-15819/quick-start/ (the M1 admonition should no longer appear)
=> DOCS-15819: Remove m1 incompatibility notice in quickstart

source/sink-connector/configuration-properties/connector-message.txt, source/sink-connector/fundamentals/error-handling-strategies.txt, source/sink-connector/fundamentals/write-strategies.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-20912
Staging:
- [Bulk write operations material](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-20912-bulk-ops-pg/sink-connector/fundamentals/write-strategies/#bulk-write-operations)
- [admonition on Error Handling fundamentals pg](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-20912-bulk-ops-pg/sink-connector/fundamentals/error-handling-strategies/#tolerate-all-errors)
- [admonition under bulk.write.ordered setting](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-20912-bulk-ops-pg/sink-connector/configuration-properties/er …
=> DOCSP-20912: create material on bulk writes

source/sink-connector/configuration-properties.txt
Corrected a link that was directing to the wrong page
Updated :doc: tags to :ref: tags
JIRA - https://jira.mongodb.org/browse/DOCSP-28267
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-28267-incorrect-link/sink-connector/configuration-properties/
- [] Did you run a spell-check?
=> DOCSP-28267 Incorrect link

source/source-connector/configuration-properties/change-stream.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-28585>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-28585-tombstone-fix/source-connector/configuration-properties/change-stream/
=> DOCPS-28585: fix tombstone on delete config setting name

source/monitoring.txt, source/tutorials/migrate-time-series.txt, source/whats-new.txt
Ran the alas_but_one.py script in this repo.
=> typo fixes surfaced by script

source/source-connector/configuration-properties/change-stream.txt
We received feedback stating that the default value for the "pipeline" change stream setting is incorrect. The [source code](https://github.com/mongodb/mongo-kafka/blob/382d72958fc083d75f0ca7fb58855cf45e2636fa/src/main/java/com/mongodb/kafka/connect/source/MongoSourceConfig.java#LL202C55-L202C55) confirms the feedback, showing that the default value should be a string rather than an array.
JIRA - https://jira.mongodb.org/browse/DOCSP-29589
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-29589-default-pipeline-value/source-connector/configuration-properties/change-stream/#settings
=> DOCSP-29589 Update pipeline default value

config/redirects
Creating a new redirect entry because the JSON formatter setting didn't get implemented until v1.3, so the new page should redirect to base for v1.2 and earlier.
=> add redirect bc json page doesnt exist before 1.3

snooty.toml
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.6/)
=> DOCSP-30859: eol-v1.6

source/includes/tutorials/feedback.rst, source/introduction/kafka-connect.txt, source/tutorials/explore-change-streams.txt, source/tutorials/migrate-time-series.txt, source/tutorials/replicate-with-cdc.txt, source/tutorials/sink-connector.txt, source/tutorials/source-connector.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-32072>
Staging - 
[Kafka and Kafka Connect](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-32072-singleton-misspellings-cleanup/introduction/kafka-connect/)
Tutorials:
- https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-32072-singleton-misspellings-cleanup/tutorials/explore-change-streams/
- https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-32072-singleton-misspellings-cleanup/tutorials/source-connector/
- https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-32072-singleton-misspellings-cleanu …
=> DOCSP-32072: atomic typo fixes and cleanup

source/source-connector/configuration-properties/kafka-topic.txt, source/source-connector/usage-examples/topic-naming.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31502>
Staging - 
[example](https://preview-mongodbrustagir.gatsbyjs.io/kafka-connector/DOCSP-31502-topic-namespace-regex/source-connector/usage-examples/topic-naming/#topic-namespace-map-with-regex-example)
[config property](https://preview-mongodbrustagir.gatsbyjs.io/kafka-connector/DOCSP-31502-topic-namespace-regex/source-connector/configuration-properties/kafka-topic/#:~:text=including%20%22.%22%2C%20%22%2D%22%2C%20and%20%22_%22-,topic.namespace.map,-Type%3A%20string)
=> DOCSP-31502: regex topic namespace mapping

source/source-connector/configuration-properties/kafka-topic.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34397>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kafka-connector/DOCSP-34397-improve-topic-prefix-desc/source-connector/configuration-properties/kafka-topic/
=> DOCSP-34397: improve desc of kafka topic prefix and suffix

source/introduction/install.txt, source/introduction/kafka-connect.txt, source/monitoring.txt, source/quick-start.txt, source/security-and-authentication/mongodb-aws-auth.txt, source/sink-connector/fundamentals/write-strategies.txt, source/source-connector/configuration-properties/startup.txt, source/source-connector/fundamentals/change-streams.txt, source/source-connector/usage-examples/copy-existing-data.txt, source/source-connector/usage-examples/custom-pipeline.txt, source/source-connector/usage-examples/schema.txt, source/tutorials/migrate-time-series.txt, source/tutorials/replicate-with-cdc.txt, source/tutorials/tutorial-setup.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33956>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kafka-connector/DOCSP-33956-kafka-alas/
=> DOCSP-33956: atomic typos fy2024-q4

source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34887>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/kafka-connector/DOCSP-34887-v1.11.1/whats-new/#std-label-kafka-connector-whats-new-1.11.1
=> DOCSP-34887: v1.11.1 release

source/source-connector/usage-examples/custom-pipeline.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-42593)
[Build Log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bf989b8e811ae6727e843e)
[Staging](https://preview-mongodblmkerbeymdb.gatsbyjs.io/kafka-connector/DOCSP-42593/source-connector/usage-examples/custom-pipeline/)
=> (DOCSP-42593) Add info about necessity of ns field.

source/includes/copy-existing-admonition.rst, source/includes/externalize-secrets.rst, source/introduction/data-formats.txt, source/sink-connector/configuration-properties/connector-message.txt, source/sink-connector/configuration-properties/error-handling.txt, source/sink-connector/configuration-properties/id-strategy.txt, source/sink-connector/configuration-properties/kafka-topic.txt, source/sink-connector/configuration-properties/mongodb-connection.txt, source/sink-connector/configuration-properties/mongodb-namespace.txt, source/sink-connector/configuration-properties/post-processors.txt, source/sink-connector/configuration-properties/time-series.txt, source/sink-connector/configuration-properties/topic-override.txt, source/source-connector/configuration-properties/change-stream.txt, source/source-connector/configuration-properties/error-handling.txt, source/source-connector/configuration-properties/kafka-topic.txt, source/source-connector/configuration-properties/mongodb-connection.txt, source/source-connector/configuration-properties/output-format.txt, source/source-connector/configuration-properties/startup.txt, source/source-connector/usage-examples/copy-existing-data.txt, source/troubleshooting/recover-from-invalid-resume-token.txt
=> (DOCSP-43962) [Kafka] Kafka connector nested components

source/includes/copy-existing-admonition.rst, source/includes/externalize-secrets.rst, source/introduction/data-formats.txt, source/sink-connector/configuration-properties/connector-message.txt, source/sink-connector/configuration-properties/error-handling.txt, source/sink-connector/configuration-properties/id-strategy.txt, source/sink-connector/configuration-properties/kafka-topic.txt, source/sink-connector/configuration-properties/mongodb-connection.txt, source/sink-connector/configuration-properties/mongodb-namespace.txt, source/sink-connector/configuration-properties/post-processors.txt, source/sink-connector/configuration-properties/time-series.txt, source/sink-connector/configuration-properties/topic-override.txt, source/source-connector/configuration-properties/change-stream.txt, source/source-connector/configuration-properties/error-handling.txt, source/source-connector/configuration-properties/kafka-topic.txt, source/source-connector/configuration-properties/mongodb-connection.txt, source/source-connector/configuration-properties/output-format.txt, source/source-connector/configuration-properties/startup.txt, source/source-connector/usage-examples/copy-existing-data.txt, source/troubleshooting/recover-from-invalid-resume-token.txt
=> (DOCSP-44165) [Kafka] Backport DOCSP-42962 to v1.10 (#167)

source/includes/copy-existing-admonition.rst, source/includes/externalize-secrets.rst, source/introduction/data-formats.txt, source/sink-connector/configuration-properties/connector-message.txt, source/sink-connector/configuration-properties/error-handling.txt, source/sink-connector/configuration-properties/id-strategy.txt, source/sink-connector/configuration-properties/kafka-topic.txt, source/sink-connector/configuration-properties/mongodb-connection.txt, source/sink-connector/configuration-properties/mongodb-namespace.txt, source/sink-connector/configuration-properties/post-processors.txt, source/sink-connector/configuration-properties/time-series.txt, source/sink-connector/configuration-properties/topic-override.txt, source/source-connector/configuration-properties/change-stream.txt, source/source-connector/configuration-properties/error-handling.txt, source/source-connector/configuration-properties/kafka-topic.txt, source/source-connector/configuration-properties/mongodb-connection.txt, source/source-connector/configuration-properties/output-format.txt, source/source-connector/configuration-properties/startup.txt, source/source-connector/usage-examples/copy-existing-data.txt, source/troubleshooting/recover-from-invalid-resume-token.txt
=> (DOCSP-43962) [Kafka] Backport DOCSP-43962 to v1.11 (#167)

source/includes/copy-existing-admonition.rst, source/includes/externalize-secrets.rst, source/introduction/data-formats.txt, source/sink-connector/configuration-properties/connector-message.txt, source/sink-connector/configuration-properties/error-handling.txt, source/sink-connector/configuration-properties/id-strategy.txt, source/sink-connector/configuration-properties/kafka-topic.txt, source/sink-connector/configuration-properties/mongodb-connection.txt, source/sink-connector/configuration-properties/mongodb-namespace.txt, source/sink-connector/configuration-properties/post-processors.txt, source/sink-connector/configuration-properties/time-series.txt, source/sink-connector/configuration-properties/topic-override.txt, source/source-connector/configuration-properties/change-stream.txt, source/source-connector/configuration-properties/error-handling.txt, source/source-connector/configuration-properties/kafka-topic.txt, source/source-connector/configuration-properties/mongodb-connection.txt, source/source-connector/configuration-properties/output-format.txt, source/source-connector/configuration-properties/startup.txt, source/source-connector/usage-examples/copy-existing-data.txt, source/troubleshooting/recover-from-invalid-resume-token.txt
=> (DOCSP-43962) [Kafka] Backport DOCSP-43962 to v1.12 (#167)

source/includes/copy-existing-admonition.rst, source/includes/externalize-secrets.rst, source/introduction/data-formats.txt, source/sink-connector/configuration-properties/connector-message.txt, source/sink-connector/configuration-properties/error-handling.txt, source/sink-connector/configuration-properties/id-strategy.txt, source/sink-connector/configuration-properties/kafka-topic.txt, source/sink-connector/configuration-properties/mongodb-connection.txt, source/sink-connector/configuration-properties/mongodb-namespace.txt, source/sink-connector/configuration-properties/post-processors.txt, source/sink-connector/configuration-properties/time-series.txt, source/sink-connector/configuration-properties/topic-override.txt, source/source-connector/configuration-properties/change-stream.txt, source/source-connector/configuration-properties/error-handling.txt, source/source-connector/configuration-properties/kafka-topic.txt, source/source-connector/configuration-properties/mongodb-connection.txt, source/source-connector/configuration-properties/output-format.txt, source/source-connector/configuration-properties/startup.txt, source/source-connector/usage-examples/copy-existing-data.txt, source/troubleshooting/recover-from-invalid-resume-token.txt
=> (DOCSP-44168) [Kafka] Backport 42962 to v1.13 (#167)

source/monitoring.txt
=> Backports DOCSP-44208: Removes nested components from last page of Kafka docs

source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45898 >
Staging - <https://deploy-preview-189--docs-kafka-connector.netlify.app/whats-new/>
=> (DOCSP-45898): release notes v1.14.1

source/introduction/connect.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31236>
Staging - <https://deploy-preview-195--docs-kafka-connector.netlify.app/introduction/connect/#prerequisites>
=> (DOCSP-31236) user role requirements for kafka connector

source/includes/copy-existing-admonition.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-45840>
Staging - <https://deploy-preview-193--docs-kafka-connector.netlify.app/source-connector/usage-examples/copy-existing-data/#copy-data>
=> (DOCSP-45840) delivery guarantee admonition missing

source/introduction/data-formats.txt, source/source-connector/usage-examples/schema.txt
This PR cherry-picks commit f095841 from master into v1.13.
JIRA - <https://jira.mongodb.org/browse/DOCSP-48448>
Staging:
- <https://deploy-preview-215--docs-kafka-connector.netlify.app/> top most section
- [Data Formats](https://deploy-preview-215--docs-kafka-connector.netlify.app//introduction/data-formats/)
- [Specify a Schema](https://deploy-preview-215--docs-kafka-connector.netlify.app/source-connector/usage-examples/schema/)
=> DOCSP-48448: Backport to v1.13

source/introduction/data-formats.txt, source/source-connector/usage-examples/schema.txt
This PR cherry-picks commit f095841 from master into v1.12.
JIRA - <https://jira.mongodb.org/browse/DOCSP-48448>
Staging:
- <https://deploy-preview-216--docs-kafka-connector.netlify.app/> top most section
- [Data Formats](https://deploy-preview-216--docs-kafka-connector.netlify.app//introduction/data-formats/)
- [Specify a Schema](https://deploy-preview-216--docs-kafka-connector.netlify.app/source-connector/usage-examples/schema/)
=> DOCSP-48448: Backport to v1.12
