mongodb/docs-kafka-connector

source/includes/m1-incompatibility.rst
source/quick-start.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-22783>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-22783-m1-notice/quick-start/

DOCSP-22783: notice for M1 incompatibility

---

source/includes/tutorials/feedback.rst
source/tutorials.txt
source/tutorials/explore-change-streams.txt
source/tutorials/migrate-time-series.txt
source/tutorials/replicate-with-cdc.txt
source/tutorials/sink-connector.txt
source/tutorials/source-connector.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-22967>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-22967-feedback-form/tutorials/explore-change-streams/

DOCSP-22967: add tutorial feedback form link

---

source/monitoring-and-logging.txt

Add Source Connector metrics from this [spreadsheet](https://docs.google.com/spreadsheets/d/1wb93gJyK0ZTpaYoGBPlBtnKyX30fOaBuYuxm084BZxY/edit#gid=0). 
JIRA - <https://jira.mongodb.org/browse/DOCSP-25294>
The content of the JMX Metrics table has already been looked over by a DevED-DBX team member and has been reviewed by DBX-JVM team. Please focus review of this table on the following:
- Formatting
- Making sure the correct columns of the table were ported (Suggested New Attribute Name, Description Edited For Docs)
Extra elaboration requested by Robert + Maxim are included in this [ticket](https://jira.mongodb.org/browse/DOCSP-25229).
For further context, see the [corresponding sink connector …

(DOCSP-25294) Port Source Metrics

---

source/whats-new.txt

Add 1.8 Whats New Section
[JIRA](https://jira.mongodb.org/browse/DOCSP-25323)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-25323-Whats-New/whats-new/)

(DOCSP-25323) What's New

---

source/includes/tutorials/robwma-m1-arch.txt
source/tutorials/explore-change-streams.txt
source/tutorials/migrate-time-series.txt
source/tutorials/replicate-with-cdc.txt
source/tutorials/sink-connector.txt
source/tutorials/source-connector.txt

All commands tested on M1. Original commands should have remained the same and continue to work.
JIRA - <https://jira.mongodb.org/browse/DOCSP-25538>
Staging:
[Explore Change Streams Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-25538-docker-command-m1/tutorials/explore-change-streams/)
[Source Connector Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-25538-docker-command-m1/tutorials/source-connector/#configure-the-source-connector)
[Sink Connector Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-25538-docker-command-m1/tutorials/sink-conn …

DOCSP-25538: Add platform to Docker commands

---

source/compatibility.txt

JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/100622-fix-source-constants/compatibility/

fix source constants for source/sink connector titles

---

snooty.toml
source/includes/tutorials/docker-success.rst
source/includes/tutorials/port-mapping-note.rst
source/includes/tutorials/quickstart-clone-commands-versioned.rst
source/includes/tutorials/robwma-m1-arch.txt
source/includes/tutorials/stop-containers.rst
source/monitoring.txt
source/quick-start.txt
source/tutorials/explore-change-streams.txt
source/tutorials/migrate-time-series.txt
source/tutorials/replicate-with-cdc.txt
source/tutorials/sink-connector.txt
source/tutorials/source-connector.txt
source/tutorials/tutorial-setup.txt

Updates docs to account for changes in sample environment in this PR: https://github.com/mongodb-university/kafka-edu/pull/30
JIRA - <https://jira.mongodb.org/browse/DOCSP-23128>
[Setup](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-23128/tutorials/tutorial-setup/)
[Change Stream](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-23128/tutorials/explore-change-streams/)
[Source](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-23128/tutorials/source-connector/)
[Sink](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-23128/tutorials/ …

(DOCSP-23128) Tutorial Updates for Sandbox Changes

---

snooty.toml
source/includes/tutorials/docker-success.rst
source/includes/tutorials/port-mapping-note.rst
source/includes/tutorials/quickstart-clone-commands-versioned.rst
source/includes/tutorials/robwma-m1-arch.txt
source/includes/tutorials/stop-containers.rst
source/quick-start.txt
source/source-connector/configuration-properties.txt
source/tutorials/explore-change-streams.txt
source/tutorials/migrate-time-series.txt
source/tutorials/replicate-with-cdc.txt
source/tutorials/sink-connector.txt
source/tutorials/source-connector.txt
source/tutorials/tutorial-setup.txt

Port https://github.com/mongodb/docs-kafka-connector/pull/33 to v1.7 branch.
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.7/)

(DOCSP-23128) Tutorial Updates for Sandbox Changes (#33)

---

source/monitoring.txt

Adds use cases for monitoring features.
[JIRA](https://jira.mongodb.org/browse/DOCSP-25140)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-25140-Monitoring-Use-Cases/monitoring/#use-cases)

(DOCSP-25140) Monitoring Use Cases

---

source/monitoring.txt

Backports https://github.com/mongodb/docs-kafka-connector/pull/24 to v1.8
JIRA - See preceding PR
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.8/monitoring/)

(DOCSP-25140) Monitoring Use Cases (#24)

---

source/includes/source-connector-change-stream.rst
source/source-connector.txt
source/source-connector/fundamentals/change-streams.txt

See #47 
https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.7/source-connector/

(DOCSP-22974) v1.7 - Move Connector Info (#47)

---

source/includes/source-connector-change-stream.rst
source/source-connector.txt
source/source-connector/fundamentals/change-streams.txt

See #47
https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.6/source-connector/

(DOCSP-22974) v1.6 - Move Connector Info (#47)

---

source/includes/source-connector-change-stream.rst
source/source-connector.txt
source/source-connector/configuration-properties.txt
source/source-connector/fundamentals/change-streams.txt

See #47 
https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.3/source-connector/

(DOCSP-22974) v1.3 Move Connector Info (#47)

---

source/includes/source-connector-change-stream.rst
source/source-connector.txt
source/source-connector/configuration-properties.txt
source/source-connector/fundamentals/change-streams.txt

See #47 
https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.2/source-connector/

(DOCSP-22974) v1.2 - Move Connector Info (#47)

---

source/includes/source-connector-change-stream.rst
source/source-connector.txt
source/source-connector/configuration-properties.txt
source/source-connector/fundamentals/change-streams.txt

See #47 
https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.1/source-connector/

(DOCSP-22974) v1.1 - Move Connector Info (#47)

---

source/includes/source-connector-change-stream.rst
source/source-connector.txt
source/source-connector/configuration-properties.txt
source/source-connector/fundamentals/change-streams.txt

See #47 
https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.0/source-connector/

(DOCSP-22974) v1.0 - Move Connector Info (#47)

---

source/source-connector/configuration-properties/output-format.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-26902
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-26902-protobuf-output-fmt/source-connector/configuration-properties/output-format/#settings

DOCSP-26902: protobuf output fmt

---

source/source-connector/configuration-properties/change-stream.txt
source/whats-new.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-26075
Staging
[Change Stream Properties](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-26075-pre-image-setting/source-connector/configuration-properties/change-stream/)
[What's New](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-26075-pre-image-setting/whats-new/#what-s-new-in-1.9)
[n/a] Are all the links working?

DOCSP-26075: pre image setting

---

snooty.toml
source/compatibility.txt
source/contribute.txt
source/includes/fundamentals/cdc/debezium.rst
source/includes/fundamentals/cdc/mongodb.rst
source/includes/source-connector-change-stream.rst
source/introduction.txt
source/introduction/connect.txt
source/introduction/install.txt
source/security-and-authentication.txt
source/security-and-authentication/mongodb-aws-auth.txt
source/security-and-authentication/tls-and-x509.txt
source/sink-connector.txt
source/sink-connector/configuration-properties.txt
source/sink-connector/fundamentals/change-data-capture.txt
source/sink-connector/fundamentals/write-strategies.txt
source/source-connector.txt
source/source-connector/configuration-properties.txt
source/source-connector/fundamentals/change-streams.txt
source/troubleshooting.txt
source/troubleshooting/recover-from-invalid-resume-token.txt

implementing constant substitutions from https://github.com/mongodb/docs-kafka-connector/pull/62 for v1.2

change constants v1.2

---

snooty.toml
source/compatibility.txt
source/contribute.txt
source/includes/fundamentals/cdc/debezium.rst
source/includes/fundamentals/cdc/mongodb.rst
source/includes/source-connector-change-stream.rst
source/introduction.txt
source/introduction/connect.txt
source/introduction/install.txt
source/security-and-authentication.txt
source/security-and-authentication/mongodb-aws-auth.txt
source/security-and-authentication/tls-and-x509.txt
source/sink-connector.txt
source/sink-connector/configuration-properties.txt
source/sink-connector/fundamentals/change-data-capture.txt
source/sink-connector/fundamentals/write-strategies.txt
source/source-connector.txt
source/source-connector/configuration-properties.txt
source/source-connector/fundamentals/change-streams.txt
source/troubleshooting.txt
source/troubleshooting/recover-from-invalid-resume-token.txt

implementing constant substitutions from https://github.com/mongodb/docs-kafka-connector/pull/62 for v1.1

change constants v1.1

---

snooty.toml
source/compatibility.txt
source/contribute.txt
source/includes/fundamentals/cdc/debezium.rst
source/includes/fundamentals/cdc/mongodb.rst
source/includes/source-connector-change-stream.rst
source/introduction.txt
source/introduction/connect.txt
source/introduction/install.txt
source/security-and-authentication.txt
source/security-and-authentication/mongodb-aws-auth.txt
source/security-and-authentication/tls-and-x509.txt
source/sink-connector.txt
source/sink-connector/configuration-properties.txt
source/sink-connector/fundamentals/change-data-capture.txt
source/sink-connector/fundamentals/write-strategies.txt
source/source-connector.txt
source/source-connector/configuration-properties.txt
source/source-connector/fundamentals/change-streams.txt
source/troubleshooting.txt
source/troubleshooting/recover-from-invalid-resume-token.txt

implementing constant substitutions from https://github.com/mongodb/docs-kafka-connector/pull/62 for v1.0

change constants v1.0

---

source/sink-connector/configuration-properties/cdc.txt
source/sink-connector/fundamentals/change-data-capture.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-19880>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-19880/sink-connector/configuration-properties/cdc/>

DOCSP-19880 - Added a link to the available CDC event handlers.

---

source/sink-connector/configuration-properties/cdc.txt
source/sink-connector/fundamentals/change-data-capture.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-19880>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-19880/sink-connector/configuration-properties/cdc/>

Changing link to a ref link

---

source/source-connector/configuration-properties/startup.txt

JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/010623-test/source-connector/configuration-properties/all-properties/#:~:text=An%20integer%20number,i%22%3A%200%7D%7D

Fix indentation

---

source/source-connector/fundamentals/specify-schema.txt
source/whats-new.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-27245
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-27245-schema-inference/source-connector/fundamentals/specify-schema/#infer-a-schema

DOCSP-27245: improved schema inference for nested docs

---

source/source-connector/configuration-properties/change-stream.txt
source/whats-new.txt

(cherry picked from commit 214f2368528041b24f4a2e6538d639b96ce67fe0)
JIRA - <https://jira.mongodb.org/browse/DOCSP-27072>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-27072/source-connector/configuration-properties/change-stream/>

Updates based on peer review.

---

source/sink-connector/configuration-properties.txt

Backport DOCSP-28267 V1.5

---

source/sink-connector/configuration-properties.txt

Backport DOCSP-28267 V1.4

---

source/sink-connector/configuration-properties.txt

Backport DOCSP-28267 V1.3

---

source/sink-connector/configuration-properties.txt

Backport DOCSP-28267 V1.2

---

source/sink-connector/configuration-properties.txt

Backport DOCSP-28267 V1.1

---

source/sink-connector/configuration-properties.txt

Backport DOCSP-28267 V1.0

---

source/sink-connector/configuration-properties/mongodb-namespace.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-28840>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-28840/sink-connector/configuration-properties/mongodb-namespace/>

DOCSP-28840: Marked collection as not required

---

source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-28911>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-28911-whats-new-update/whats-new/#std-label-kafka-connector-whats-new-1.10>

DOCSP-28911: Added bullet for what's new

---

source/source-connector/configuration-properties/change-stream.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-28900>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-28900/source-connector/configuration-properties/change-stream/#settings>

DOCSP-28900: Updates description of poll.await.time.ms

---

source/includes/properties-files/converters/avro-sink.properties
source/includes/properties-files/converters/avro-source.properties
source/includes/properties-files/converters/json-schema-sink.properties
source/includes/properties-files/converters/json-schema-source.properties
source/includes/properties-files/converters/protobuf-sink.properties

* DOCSP-30132 bug reported on key converter
* DOCSP-30132 bug reported on key converter source
* Update .gitignore
---------
Co-authored-by: Caitlin Davey <caitlin.davey@mongodb.com>
(cherry picked from commit 5f745c884953846dc57598c9db625a1be2995874)

DOCSP-30132 bug reported on key converter (#117)

---

snooty.toml

[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.0/)

DOCSP-30859: eol-v1.0

---

snooty.toml

[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.2/)

DOCSP-30859: eol-v1.2

---

snooty.toml

[Staging](https://docs-mongodborg-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.1/)

DOCSP-30859: eol-v1.1

---

snooty.toml

[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.7/)

DOCSP-30859: eol-v1.7

---

snooty.toml

[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.3/)

DOCSP-30859-eol-v1.3

---

snooty.toml

[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.4/)

DOCSP-30859: eol-v1.4

---

snooty.toml

[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/v1.5/)

DOCSP-30859: eol-v1.5

---

source/index.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-30439>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-30439-hosting-partners/

DOCSP-30439: add hosting partners

---

source/index.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-33044>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/kafka-connector/DOCSP-33044-atlas-stream-processing/

DOCSP-33044: Atlas Stream Processing callout

---

source/index.txt

Copy was discussed with Program Lead, but any reviewers should feel free to point out style guide issues.
JIRA - <https://jira.mongodb.org/browse/DOCSP-30439>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/kafka-connector/DOCSP-30439-add-additional-confluent-links/

DOCSP-30439: Add Partner Links

---

source/index.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-33332>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/kafka-connector/DOCSP-33332-fix-confluent-sink-connector-link/

DOCSP-33332: fix confluent sink connector link

---

source/sink-connector/configuration-properties/write-strategies.txt
source/sink-connector/fundamentals/write-strategies.txt
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-32089>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kafka-connector/DOCSP-32089-updateonedefault-strategy/sink-connector/configuration-properties/write-strategies/#:~:text=model%20strategies.-,UpdateOneDefaultStrategy,-Description%3A

DOCSP-32089: add update write model strategy

---

source/sink-connector/configuration-properties/write-strategies.txt
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-29571>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kafka-connector/DOCSP-29571-delete-writemodel/sink-connector/configuration-properties/write-strategies/#overview

DOCSP-29571: delete writemodel

---

snooty.toml

JIRA - <https://jira.mongodb.org/browse/DOCSP-35628>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kafka-connector/v1.8/

DOCSP-35628: EOL v1.8

---

snooty.toml

JIRA - <https://jira.mongodb.org/browse/DOCSP-35628>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kafka-connector/v1.9/

DOCSP-35628: EOL v1.9

---

source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-36929>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/kafka-connector/DOCSP-36929-version-updates/whats-new/>

DOCSP-36929: 1.11.2 version updates

---

config/redirects
snooty.toml

JIRA - https://jira.mongodb.org/browse/DOCSP-40148
Staging - https://preview-mongodbmongokart.gatsbyjs.io/kafka-connector/docsp-40148-version-1.13/introduction/install/

DOCSP-40148 - v1.13 bump

---

source/includes/fundamentals/cdc/debezium.rst

JIRA - <https://jira.mongodb.org/browse/DOCSP-38228>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kafka-connector/DOCSP-38228-debezium-cdc/sink-connector/fundamentals/change-data-capture/>

DOCSP-38228: Debezium configuration property update

---

source/introduction/connect.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-42379>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kafka-connector/DOCSP-42379-placeholders/introduction/connect/>

DOCSP-42379: Update username/password placeholders

---

source/monitoring.txt

Backports DOCSP-44208: Removes nested components from last page of Kafka docs

---

source/quick-start.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-NNNNN
Staging -

DOCSP-42898 -- backport to v1.13

---

source/quick-start.txt

[JIRA](https://jira.mongodb.org/browse/DOCSP-42898)
[Staging](https://deploy-preview-177--docs-kafka-connector.netlify.app/quick-start/#start-the-sandbox)

DOCSP-42898 -- Update docker compose command

---

source/whats-new.txt

This will backport the following commits from `master` to `v1.14`:
- [Merge pull request #189 from davidhou17/DOCSP-45898](https://github.com/mongodb/docs-kafka-connector/pull/189)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

[v1.14] Merge pull request #189 from davidhou17/DOCSP-45898

---

source/source-connector/configuration-properties/change-stream.txt
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-46645>
Staging: 
- <https://deploy-preview-196--docs-kafka-connector.netlify.app/source-connector/configuration-properties/change-stream/>
- <https://deploy-preview-196--docs-kafka-connector.netlify.app/whats-new/>

DOCSP-46645 v1.15.0 updates

---

source/sink-connector/configuration-properties.txt
source/sink-connector/configuration-properties/kafka-topic.txt
source/sink-connector/fundamentals.txt
source/source-connector/configuration-properties.txt
source/source-connector/configuration-properties/kafka-topic.txt
source/source-connector/fundamentals.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-48224>
Staging 
- Fundamentals: <https://deploy-preview-198--docs-kafka-connector.netlify.app/sink-connector/fundamentals/>
- Kafka Topics: <https://deploy-preview-198--docs-kafka-connector.netlify.app/sink-connector/configuration-properties/kafka-topic/>

DOCSP-48224 Duplicate titles: Fundamentals and Topics

---

source/includes/usage-examples/copy/multisource.json
source/includes/usage-examples/copy/multisource.properties
source/introduction/connect.txt
source/source-connector/usage-examples/copy-existing-data.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-36972>
Staging - <https://deploy-preview-199--docs-kafka-connector.netlify.app/source-connector/usage-examples/copy-existing-data/>

DOCSP-36972: Copy data from multiple sources

---

source/introduction/data-formats.txt
source/source-connector/usage-examples/schema.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-48448>
Staging:
- <https://deploy-preview-202--docs-kafka-connector.netlify.app/> top most section
- [Data Formats](https://deploy-preview-202--docs-kafka-connector.netlify.app/introduction/data-formats/)
- [Specify a Schema](https://deploy-preview-202--docs-kafka-connector.netlify.app/source-connector/usage-examples/schema/)

Updates outdated links to Apache Avro spec

---

source/introduction/data-formats.txt
source/source-connector/usage-examples/schema.txt

This PR cherry-picks commit f095841 from master into v1.15.

DOCSP-48448: Backport to v1.15
